; A Harmless Grenade, AKG format, v1.0.

; Generated by Arkos Tracker 2.

AHarmlessGrenade_Start:


AHarmlessGrenade_DisarkByteRegionStart0:
	defb "AT20"
AHarmlessGrenade_DisarkPointerRegionStart1:
	defw AHarmlessGrenade_ArpeggioTable	; The address of the Arpeggio table.
	defw AHarmlessGrenade_PitchTable	; The address of the Pitch table.
	defw AHarmlessGrenade_InstrumentTable	; The address of the Instrument table.
	defw AHarmlessGrenade_EffectBlockTable	; The address of the Effect Block table.
AHarmlessGrenade_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
AHarmlessGrenade_DisarkPointerRegionStart2:
	defw AHarmlessGrenade_Subsong0_Start
AHarmlessGrenade_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
AHarmlessGrenade_ArpeggioTable:
AHarmlessGrenade_DisarkPointerRegionStart3:
	defw AHarmlessGrenade_Arpeggio1
	defw AHarmlessGrenade_Arpeggio2
AHarmlessGrenade_DisarkPointerRegionEnd3:

AHarmlessGrenade_Arpeggio1:
	defb 1	; The speed.

	defb 0
	defb 12
	defb 9
	defb -12
	defb 18
	defb -128
AHarmlessGrenade_DisarkWordForceReference4:
	defw AHarmlessGrenade_Arpeggio1 + 0 + 1	; Loop.

AHarmlessGrenade_Arpeggio2:
	defb 1	; The speed.

	defb 0
	defb 6
	defb -3
	defb -12
	defb -6
	defb 0
	defb 12
	defb -128
AHarmlessGrenade_DisarkWordForceReference5:
	defw AHarmlessGrenade_Arpeggio2 + 0 + 1	; Loop.

; Declares all the Pitches.
AHarmlessGrenade_PitchTable:
AHarmlessGrenade_DisarkPointerRegionStart6:
	defw AHarmlessGrenade_Pitch1
AHarmlessGrenade_DisarkPointerRegionEnd6:

AHarmlessGrenade_Pitch1:
	defb 2	; The speed.

	defw 0
AHarmlessGrenade_Pitch1_GotoNextForLine0:
AHarmlessGrenade_DisarkWordForceReference7:
	defw AHarmlessGrenade_Pitch1_GotoNextForLine0 + 2
	defw 0
AHarmlessGrenade_Pitch1_GotoNextForLine1:
AHarmlessGrenade_DisarkWordForceReference8:
	defw AHarmlessGrenade_Pitch1_GotoNextForLine1 + 2
	defw 0
AHarmlessGrenade_Pitch1_GotoNextForLine2:
AHarmlessGrenade_DisarkWordForceReference9:
	defw AHarmlessGrenade_Pitch1_GotoNextForLine2 + 2
	defw -1
AHarmlessGrenade_Pitch1_GotoNextForLine3:
AHarmlessGrenade_DisarkWordForceReference10:
	defw AHarmlessGrenade_Pitch1_GotoNextForLine3 + 2
	defw -4
AHarmlessGrenade_Pitch1_GotoNextForLine4:
AHarmlessGrenade_DisarkWordForceReference11:
	defw AHarmlessGrenade_Pitch1_GotoNextForLine4 + 2
	defw 2
AHarmlessGrenade_DisarkWordForceReference12:
	defw AHarmlessGrenade_Pitch1 + 4 * 2 + 1

; Declares all the Instruments.
AHarmlessGrenade_InstrumentTable:
AHarmlessGrenade_DisarkPointerRegionStart13:
	defw AHarmlessGrenade_EmptyInstrument
	defw AHarmlessGrenade_Instrument1
	defw AHarmlessGrenade_Instrument2
	defw AHarmlessGrenade_Instrument3
	defw AHarmlessGrenade_Instrument4
	defw AHarmlessGrenade_Instrument5
	defw AHarmlessGrenade_Instrument6
	defw AHarmlessGrenade_Instrument7
	defw AHarmlessGrenade_Instrument8
	defw AHarmlessGrenade_Instrument9
	defw AHarmlessGrenade_Instrument10
	defw AHarmlessGrenade_Instrument11
	defw AHarmlessGrenade_Instrument12
	defw AHarmlessGrenade_Instrument13
	defw AHarmlessGrenade_Instrument14
	defw AHarmlessGrenade_Instrument15
	defw AHarmlessGrenade_Instrument16
	defw AHarmlessGrenade_Instrument17
	defw AHarmlessGrenade_Instrument18
	defw AHarmlessGrenade_Instrument19
AHarmlessGrenade_DisarkPointerRegionEnd13:

AHarmlessGrenade_EmptyInstrument:
	defb 0	; The speed (>0, 0 for 256).
AHarmlessGrenade_EmptyInstrument_Loop:
	defb 0	; No Soft no Hard. Volume: 0. Noise? false.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument1:
	defb 2	; The speed (>0, 0 for 256).
	defb 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	defb 34	; Complex case. Ratio: 5
	defb 12	; Arpeggio.

	defb 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	defb 36	; Complex case. Ratio: 3
	defb 12	; Arpeggio.

	defb 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	defb 36	; Complex case. Ratio: 3
	defb 12	; Arpeggio.

	defb 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	defb 130	; Simple case. Ratio: 5

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 209	; Soft only. Volume: 10. Volume only.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument2:
	defb 1	; The speed (>0, 0 for 256).
	defb 121	; Soft only. Volume: 15.
	defb 2	; Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	defb 121	; Soft only. Volume: 15.
	defb 33	; Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	defw 32	; Pitch.

	defb 121	; Soft only. Volume: 15.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 48	; Pitch.

	defb 121	; Soft only. Volume: 15.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 68	; Pitch.

	defb 121	; Soft only. Volume: 15.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 116	; Pitch.

	defb 121	; Soft only. Volume: 15.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 228	; Pitch.

	defb 113	; Soft only. Volume: 14.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 180	; Pitch.

	defb 105	; Soft only. Volume: 13.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 292	; Pitch.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument3:
	defb 1	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 1	; Noise: 1.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 1	; Noise: 1.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument4:
	defb 1	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 4	; Noise: 4.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument5:
	defb 1	; The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument5_Loop:
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 1	; Noise: 1.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 1	; Noise: 1.

	defb 176	; No Soft no Hard. Volume: 6. Noise? true.
	defb 1	; Noise: 1.

	defb 7	; Loop.
AHarmlessGrenade_DisarkWordForceReference14:
	defw AHarmlessGrenade_Instrument5_Loop	; Loop here.

AHarmlessGrenade_Instrument6:
	defb 4	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument7:
	defb 3	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 209	; Soft only. Volume: 10. Volume only.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 193	; Soft only. Volume: 8. Volume only.

	defb 185	; Soft only. Volume: 7. Volume only.

	defb 177	; Soft only. Volume: 6. Volume only.

	defb 169	; Soft only. Volume: 5. Volume only.

	defb 161	; Soft only. Volume: 4. Volume only.

	defb 153	; Soft only. Volume: 3. Volume only.

	defb 145	; Soft only. Volume: 2. Volume only.

	defb 137	; Soft only. Volume: 1. Volume only.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument8:
	defb 1	; The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument8_Loop:
	defb 34	; Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	defb 131	; Simple case. Ratio: 4

	defb 7	; Loop.
AHarmlessGrenade_DisarkWordForceReference15:
	defw AHarmlessGrenade_Instrument8_Loop	; Loop here.

AHarmlessGrenade_Instrument9:
	defb 1	; The speed (>0, 0 for 256).
	defb 248	; No Soft no Hard. Volume: 15. Noise? true.
	defb 2	; Noise: 2.

	defb 241	; Soft only. Volume: 14. Volume only.

	defb 105	; Soft only. Volume: 13.
	defb 33	; Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	defw 208	; Pitch.

	defb 89	; Soft only. Volume: 11.
	defb 33	; Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	defw 400	; Pitch.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 1	; Noise: 1.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 3	; Noise: 3.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 4	; Noise: 4.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 1	; Noise: 1.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument10:
	defb 5	; The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument10_Loop:	defb 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	defb 130	; Simple case. Ratio: 5

	defb 7	; Loop.
AHarmlessGrenade_DisarkWordForceReference16:
	defw AHarmlessGrenade_Instrument10_Loop	; Loop here.

AHarmlessGrenade_Instrument11:
	defb 2	; The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument11_Loop:
	defb 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	defb 35	; Complex case. Ratio: 4
	defb 12	; Arpeggio.

	defb 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	defb 35	; Complex case. Ratio: 4
	defb 12	; Arpeggio.

	defb 120	; No Soft no Hard. Volume: 15. Noise? false.

	defb 7	; Loop.
AHarmlessGrenade_DisarkWordForceReference17:
	defw AHarmlessGrenade_Instrument11_Loop	; Loop here.

AHarmlessGrenade_Instrument12:
	defb 1	; The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument12_Loop:
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 7	; Loop.
AHarmlessGrenade_DisarkWordForceReference18:
	defw AHarmlessGrenade_Instrument12_Loop	; Loop here.

AHarmlessGrenade_Instrument13:
	defb 1	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument14:
	defb 1	; The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument14_Loop:
	defb 34	; Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	defb 132	; Simple case. Ratio: 3

	defb 7	; Loop.
AHarmlessGrenade_DisarkWordForceReference19:
	defw AHarmlessGrenade_Instrument14_Loop	; Loop here.

AHarmlessGrenade_Instrument15:
	defb 2	; The speed (>0, 0 for 256).
	defb 249	; Soft only. Volume: 15. Volume only.

AHarmlessGrenade_Instrument15_Loop:
	defb 113	; Soft only. Volume: 14.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw -5	; Pitch.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 5	; Pitch.

	defb 249	; Soft only. Volume: 15. Volume only.

	defb 105	; Soft only. Volume: 13.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw -7	; Pitch.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 81	; Soft only. Volume: 10.
	defb 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	defw 32	; Pitch.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 241	; Soft only. Volume: 14. Volume only.

	defb 7	; Loop.
AHarmlessGrenade_DisarkWordForceReference20:
	defw AHarmlessGrenade_Instrument15_Loop	; Loop here.

AHarmlessGrenade_Instrument16:
	defb 1	; The speed (>0, 0 for 256).
	defb 232	; No Soft no Hard. Volume: 13. Noise? true.
	defb 5	; Noise: 5.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 5	; Noise: 5.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 5	; Noise: 5.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 5	; Noise: 5.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 5	; Noise: 5.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument17:
	defb 1	; The speed (>0, 0 for 256).
	defb 232	; No Soft no Hard. Volume: 13. Noise? true.
	defb 9	; Noise: 9.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 9	; Noise: 9.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 9	; Noise: 9.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 9	; Noise: 9.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 9	; Noise: 9.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument18:
	defb 1	; The speed (>0, 0 for 256).
	defb 232	; No Soft no Hard. Volume: 13. Noise? true.
	defb 17	; Noise: 17.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 17	; Noise: 17.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 17	; Noise: 17.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 17	; Noise: 17.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 17	; Noise: 17.

	defb 6	; Loop to silence.

AHarmlessGrenade_Instrument19:
	defb 1	; The speed (>0, 0 for 256).
	defb 232	; No Soft no Hard. Volume: 13. Noise? true.
	defb 25	; Noise: 25.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 25	; Noise: 25.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 25	; Noise: 25.

	defb 200	; No Soft no Hard. Volume: 9. Noise? true.
	defb 25	; Noise: 25.

	defb 184	; No Soft no Hard. Volume: 7. Noise? true.
	defb 25	; Noise: 25.

	defb 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
AHarmlessGrenade_EffectBlockTable:
AHarmlessGrenade_DisarkPointerRegionStart21:
	defw AHarmlessGrenade_EffectBlock_P20P0P32	; Index 0
	defw AHarmlessGrenade_EffectBlock_P4P3	; Index 1
	defw AHarmlessGrenade_EffectBlock_P4P0	; Index 2
	defw AHarmlessGrenade_EffectBlock_P4P2	; Index 3
	defw AHarmlessGrenade_EffectBlock_P4P1	; Index 4
	defw AHarmlessGrenade_EffectBlock_P24P26P255P15	; Index 5
	defw AHarmlessGrenade_EffectBlock_P28P48	; Index 6
	defw AHarmlessGrenade_EffectBlock_P0	; Index 7
	defw AHarmlessGrenade_EffectBlock_P3P5P21P0P2P6P1	; Index 8
	defw AHarmlessGrenade_EffectBlock_P4P4	; Index 9
	defw AHarmlessGrenade_EffectBlock_P20P0P16	; Index 10
	defw AHarmlessGrenade_EffectBlock_P28P51	; Index 11
	defw AHarmlessGrenade_EffectBlock_P28P57	; Index 12
	defw AHarmlessGrenade_EffectBlock_P4P5	; Index 13
	defw AHarmlessGrenade_EffectBlock_P3P2P10P0	; Index 14
	defw AHarmlessGrenade_EffectBlock_P5P2P10P0	; Index 15
	defw AHarmlessGrenade_EffectBlock_P3P2P6P0	; Index 16
	defw AHarmlessGrenade_EffectBlock_P28P54	; Index 17
	defw AHarmlessGrenade_EffectBlock_P28P58	; Index 18
	defw AHarmlessGrenade_EffectBlock_P14P0P1	; Index 19
	defw AHarmlessGrenade_EffectBlock_P20P0P80	; Index 20
	defw AHarmlessGrenade_EffectBlock_P2P2	; Index 21
	defw AHarmlessGrenade_EffectBlock_P2P4	; Index 22
	defw AHarmlessGrenade_EffectBlock_P4P6	; Index 23
	defw AHarmlessGrenade_EffectBlock_P28P55	; Index 24
AHarmlessGrenade_DisarkPointerRegionEnd21:

AHarmlessGrenade_EffectBlock_P0:
	defb 0
AHarmlessGrenade_EffectBlock_P2P2:
	defb 2, 2
AHarmlessGrenade_EffectBlock_P2P4:
	defb 2, 4
AHarmlessGrenade_EffectBlock_P4P0:
	defb 4, 0
AHarmlessGrenade_EffectBlock_P4P1:
	defb 4, 1
AHarmlessGrenade_EffectBlock_P4P2:
	defb 4, 2
AHarmlessGrenade_EffectBlock_P4P3:
	defb 4, 3
AHarmlessGrenade_EffectBlock_P4P4:
	defb 4, 4
AHarmlessGrenade_EffectBlock_P4P5:
	defb 4, 5
AHarmlessGrenade_EffectBlock_P4P6:
	defb 4, 6
AHarmlessGrenade_EffectBlock_P3P2P10P0:
	defb 3, 2, 10, 0
AHarmlessGrenade_EffectBlock_P5P2P10P0:
	defb 5, 2, 10, 0
AHarmlessGrenade_EffectBlock_P24P26P255P15:
	defb 24, 26, 255, 15
AHarmlessGrenade_EffectBlock_P3P5P21P0P2P6P1:
	defb 3, 5, 21, 0, 2, 6, 1
AHarmlessGrenade_EffectBlock_P14P0P1:
	defb 14, 0, 1
AHarmlessGrenade_EffectBlock_P3P2P6P0:
	defb 3, 2, 6, 0
AHarmlessGrenade_EffectBlock_P20P0P16:
	defb 20, 0, 16
AHarmlessGrenade_EffectBlock_P20P0P32:
	defb 20, 0, 32
AHarmlessGrenade_EffectBlock_P20P0P80:
	defb 20, 0, 80
AHarmlessGrenade_EffectBlock_P28P48:
	defb 28, 48
AHarmlessGrenade_EffectBlock_P28P51:
	defb 28, 51
AHarmlessGrenade_EffectBlock_P28P54:
	defb 28, 54
AHarmlessGrenade_EffectBlock_P28P55:
	defb 28, 55
AHarmlessGrenade_EffectBlock_P28P57:
	defb 28, 57
AHarmlessGrenade_EffectBlock_P28P58:
	defb 28, 58

AHarmlessGrenade_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
AHarmlessGrenade_Subsong0_DisarkByteRegionStart0:
AHarmlessGrenade_Subsong0_Start:
	defb 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	defb 0	; Digichannel (0-2).
	defb 1	; PSG count (>0).
	defb 0	; Loop start index (>=0).
	defb 23	; End index (>=0).
	defb 6	; Initial speed (>=0).
	defb 5	; Base note index (>=0).

AHarmlessGrenade_Subsong0_Linker:
AHarmlessGrenade_Subsong0_DisarkPointerRegionStart1:
; Position 0
AHarmlessGrenade_Subsong0_Linker_Loop:
	defw AHarmlessGrenade_Subsong0_Track0
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 1
	defw AHarmlessGrenade_Subsong0_Track0
	defw AHarmlessGrenade_Subsong0_Track1
	defw AHarmlessGrenade_Subsong0_Track1
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 2
	defw AHarmlessGrenade_Subsong0_Track0
	defw AHarmlessGrenade_Subsong0_Track1
	defw AHarmlessGrenade_Subsong0_Track2
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 3
	defw AHarmlessGrenade_Subsong0_Track0
	defw AHarmlessGrenade_Subsong0_Track1
	defw AHarmlessGrenade_Subsong0_Track2
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 4
	defw AHarmlessGrenade_Subsong0_Track3
	defw AHarmlessGrenade_Subsong0_Track5
	defw AHarmlessGrenade_Subsong0_Track4
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 5
	defw AHarmlessGrenade_Subsong0_Track6
	defw AHarmlessGrenade_Subsong0_Track8
	defw AHarmlessGrenade_Subsong0_Track7
	defw AHarmlessGrenade_Subsong0_LinkerBlock1

; Position 6
	defw AHarmlessGrenade_Subsong0_Track9
	defw AHarmlessGrenade_Subsong0_Track10
	defw AHarmlessGrenade_Subsong0_Track11
	defw AHarmlessGrenade_Subsong0_LinkerBlock2

; Position 7
	defw AHarmlessGrenade_Subsong0_Track6
	defw AHarmlessGrenade_Subsong0_Track8
	defw AHarmlessGrenade_Subsong0_Track7
	defw AHarmlessGrenade_Subsong0_LinkerBlock1

; Position 8
	defw AHarmlessGrenade_Subsong0_Track12
	defw AHarmlessGrenade_Subsong0_Track13
	defw AHarmlessGrenade_Subsong0_Track14
	defw AHarmlessGrenade_Subsong0_LinkerBlock2

; Position 9
	defw AHarmlessGrenade_Subsong0_Track6
	defw AHarmlessGrenade_Subsong0_Track8
	defw AHarmlessGrenade_Subsong0_Track7
	defw AHarmlessGrenade_Subsong0_LinkerBlock1

; Position 10
	defw AHarmlessGrenade_Subsong0_Track9
	defw AHarmlessGrenade_Subsong0_Track10
	defw AHarmlessGrenade_Subsong0_Track11
	defw AHarmlessGrenade_Subsong0_LinkerBlock2

; Position 11
	defw AHarmlessGrenade_Subsong0_Track15
	defw AHarmlessGrenade_Subsong0_Track16
	defw AHarmlessGrenade_Subsong0_Track17
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 12
	defw AHarmlessGrenade_Subsong0_Track15
	defw AHarmlessGrenade_Subsong0_Track16
	defw AHarmlessGrenade_Subsong0_Track20
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 13
	defw AHarmlessGrenade_Subsong0_Track15
	defw AHarmlessGrenade_Subsong0_Track16
	defw AHarmlessGrenade_Subsong0_Track17
	defw AHarmlessGrenade_Subsong0_LinkerBlock3

; Position 14
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_Track23
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_LinkerBlock4

; Position 15
	defw AHarmlessGrenade_Subsong0_Track18
	defw AHarmlessGrenade_Subsong0_Track19
	defw AHarmlessGrenade_Subsong0_Track21
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 16
	defw AHarmlessGrenade_Subsong0_Track18
	defw AHarmlessGrenade_Subsong0_Track19
	defw AHarmlessGrenade_Subsong0_Track21
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 17
	defw AHarmlessGrenade_Subsong0_Track24
	defw AHarmlessGrenade_Subsong0_Track19
	defw AHarmlessGrenade_Subsong0_Track21
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 18
	defw AHarmlessGrenade_Subsong0_Track24
	defw AHarmlessGrenade_Subsong0_Track19
	defw AHarmlessGrenade_Subsong0_Track21
	defw AHarmlessGrenade_Subsong0_LinkerBlock0

; Position 19
	defw AHarmlessGrenade_Subsong0_Track24
	defw AHarmlessGrenade_Subsong0_Track19
	defw AHarmlessGrenade_Subsong0_Track21
	defw AHarmlessGrenade_Subsong0_LinkerBlock5

; Position 20
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_Track23
	defw AHarmlessGrenade_Subsong0_Track25
	defw AHarmlessGrenade_Subsong0_LinkerBlock6

; Position 21
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_Track23
	defw AHarmlessGrenade_Subsong0_Track25
	defw AHarmlessGrenade_Subsong0_LinkerBlock7

; Position 22
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_Track23
	defw AHarmlessGrenade_Subsong0_Track25
	defw AHarmlessGrenade_Subsong0_LinkerBlock8

; Position 23
	defw AHarmlessGrenade_Subsong0_Track22
	defw AHarmlessGrenade_Subsong0_Track23
	defw AHarmlessGrenade_Subsong0_Track25
	defw AHarmlessGrenade_Subsong0_LinkerBlock9

AHarmlessGrenade_Subsong0_DisarkPointerRegionEnd1:
	defw 0	; Loop.
AHarmlessGrenade_Subsong0_DisarkWordForceReference2:
	defw AHarmlessGrenade_Subsong0_Linker_Loop

AHarmlessGrenade_Subsong0_LinkerBlock0:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference3:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference4:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock1:
	defb 24	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference5:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference6:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock2:
	defb 8	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference7:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference8:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock3:
	defb 28	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference9:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference10:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock4:
	defb 4	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference11:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference12:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock5:
	defb 16	; Height.
	defb 2	; Transposition 0.
	defb 0	; Transposition 1.
	defb 2	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference13:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference14:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock6:
	defb 4	; Height.
	defb 0	; Transposition 0.
	defb 2	; Transposition 1.
	defb 0	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference15:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference16:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock7:
	defb 4	; Height.
	defb 0	; Transposition 0.
	defb 10	; Transposition 1.
	defb 4	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference17:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference18:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock8:
	defb 4	; Height.
	defb 0	; Transposition 0.
	defb 20	; Transposition 1.
	defb 8	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference19:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference20:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock9:
	defb 4	; Height.
	defb 0	; Transposition 0.
	defb 36	; Transposition 1.
	defb 14	; Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference21:
	defw AHarmlessGrenade_Subsong0_SpeedTrack0	; SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference22:
	defw AHarmlessGrenade_Subsong0_EventTrack0	; EventTrack address.

AHarmlessGrenade_Subsong0_Track0:
	defb 146
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 18
	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 18
	defb 18
	defb 21
	defb 24
	defb 27
	defb 30
	defb 24
	defb 19
	defb 21
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track1:
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track2:
	defb 211
	defb 2	; New Instrument (2).
	defb 7	; Index to an effect block.
	defb 211
	defb 3	; New Instrument (3).
	defb 1	; Index to an effect block.
	defb 83
	defb 2	; Index to an effect block.
	defb 83
	defb 1	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 211
	defb 4	; New Instrument (4).
	defb 4	; Index to an effect block.
	defb 211
	defb 3	; New Instrument (3).
	defb 3	; Index to an effect block.
	defb 83
	defb 1	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 211
	defb 5	; New Instrument (5).
	defb 4	; Index to an effect block.
	defb 211
	defb 3	; New Instrument (3).
	defb 3	; Index to an effect block.
	defb 211
	defb 4	; New Instrument (4).
	defb 1	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 211
	defb 6	; New Instrument (6).
	defb 1	; Index to an effect block.
	defb 211
	defb 4	; New Instrument (4).
	defb 13	; Index to an effect block.
	defb 211
	defb 6	; New Instrument (6).
	defb 3	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 211
	defb 3	; New Instrument (3).
	defb 3	; Index to an effect block.
	defb 211
	defb 4	; New Instrument (4).
	defb 4	; Index to an effect block.
	defb 211
	defb 3	; New Instrument (3).
	defb 1	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 211
	defb 4	; New Instrument (4).
	defb 3	; Index to an effect block.
	defb 211
	defb 5	; New Instrument (5).
	defb 1	; Index to an effect block.
	defb 211
	defb 4	; New Instrument (4).
	defb 4	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 211
	defb 3	; New Instrument (3).
	defb 4	; Index to an effect block.
	defb 211
	defb 5	; New Instrument (5).
	defb 1	; Index to an effect block.
	defb 83
	defb 9	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 211
	defb 3	; New Instrument (3).
	defb 9	; Index to an effect block.
	defb 211
	defb 4	; New Instrument (4).
	defb 3	; Index to an effect block.
	defb 147
	defb 6	; New Instrument (6).
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track3:
	defb 255
	defb 79	; Escape note (79).
	defb 7	; New Instrument (7).
	defb 14	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 63
	defb 77	; Escape note (77).
	defb 61, 6	; Waits for 7 lines.

	defb 63
	defb 72	; Escape note (72).
	defb 61, 6	; Waits for 7 lines.

	defb 63
	defb 76	; Escape note (76).
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track4:
	defb 211
	defb 2	; New Instrument (2).
	defb 7	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 255
	defb 75	; Escape note (75).
	defb 7	; New Instrument (7).
	defb 15	; Index to an effect block.
	defb 61, 6	; Waits for 7 lines.

	defb 63
	defb 71	; Escape note (71).
	defb 61, 6	; Waits for 7 lines.

	defb 63
	defb 77	; Escape note (77).
	defb 61, 6	; Waits for 7 lines.

	defb 63
	defb 79	; Escape note (79).
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track5:
	defb 146
	defb 8	; New Instrument (8).
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track6:
	defb 222
	defb 10	; New Instrument (10).
	defb 7	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 30
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 30
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 128
	defb 0	; New Instrument (0).
	defb 61, 5	; Waits for 6 lines.

	defb 146
	defb 10	; New Instrument (10).
	defb 30
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 30
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 30
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track7:
	defb 210
	defb 12	; New Instrument (12).
	defb 7	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 18
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 18
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 128
	defb 0	; New Instrument (0).
	defb 61, 5	; Waits for 6 lines.

	defb 210
	defb 12	; New Instrument (12).
	defb 19	; Index to an effect block.
	defb 82
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 18
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 18
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track8:
	defb 211
	defb 2	; New Instrument (2).
	defb 7	; Index to an effect block.
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 60	; Waits for 1 line.

	defb 163
	defb 9	; New Instrument (9).
	defb 99
	defb 4	; Index to an effect block.
	defb 99
	defb 3	; Index to an effect block.
	defb 99
	defb 1	; Index to an effect block.
	defb 99
	defb 9	; Index to an effect block.
	defb 99
	defb 13	; Index to an effect block.
	defb 99
	defb 23	; Index to an effect block.
	defb 211
	defb 2	; New Instrument (2).
	defb 2	; Index to an effect block.
	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track9:
	defb 144
	defb 10	; New Instrument (10).
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 5	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track10:
	defb 159
	defb 9	; New Instrument (9).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 159
	defb 9	; New Instrument (9).
	defb 147
	defb 2	; New Instrument (2).
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track11:
	defb 144
	defb 12	; New Instrument (12).
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 5	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track12:
	defb 142
	defb 10	; New Instrument (10).
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 10	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 11
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track13:
	defb 211
	defb 2	; New Instrument (2).
	defb 7	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 19
	defb 223
	defb 4	; New Instrument (4).
	defb 1	; Index to an effect block.
	defb 223
	defb 6	; New Instrument (6).
	defb 4	; Index to an effect block.
	defb 223
	defb 3	; New Instrument (3).
	defb 3	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track14:
	defb 142
	defb 12	; New Instrument (12).
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 10	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 11
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track15:
	defb 162
	defb 14	; New Instrument (14).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 31
	defb 61, 8	; Waits for 9 lines.

	defb 153
	defb 8	; New Instrument (8).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 22
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track16:
	defb 147
	defb 2	; New Instrument (2).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 60	; Waits for 1 line.

	defb 19
	defb 159
	defb 9	; New Instrument (9).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 19
	defb 60	; Waits for 1 line.

	defb 19
	defb 159
	defb 9	; New Instrument (9).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 147
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 159
	defb 9	; New Instrument (9).
	defb 147
	defb 2	; New Instrument (2).
	defb 60	; Waits for 1 line.

	defb 19
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track17:
	defb 235
	defb 13	; New Instrument (13).
	defb 22	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 53
	defb 60	; Waits for 1 line.

	defb 52
	defb 60	; Waits for 1 line.

	defb 107
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 53
	defb 60	; Waits for 1 line.

	defb 116
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 52
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track18:
	defb 150
	defb 11	; New Instrument (11).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 19
	defb 61, 8	; Waits for 9 lines.

	defb 13
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 10
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track19:
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 16	; New Instrument (16).
	defb 43
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 16	; New Instrument (16).
	defb 147
	defb 2	; New Instrument (2).
	defb 159
	defb 9	; New Instrument (9).
	defb 171
	defb 16	; New Instrument (16).
	defb 43
	defb 43
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 17	; New Instrument (17).
	defb 43
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 17	; New Instrument (17).
	defb 43
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 17	; New Instrument (17).
	defb 171
	defb 18	; New Instrument (18).
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 18	; New Instrument (18).
	defb 147
	defb 2	; New Instrument (2).
	defb 159
	defb 9	; New Instrument (9).
	defb 171
	defb 18	; New Instrument (18).
	defb 171
	defb 19	; New Instrument (19).
	defb 43
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 19	; New Instrument (19).
	defb 159
	defb 9	; New Instrument (9).
	defb 147
	defb 2	; New Instrument (2).
	defb 171
	defb 19	; New Instrument (19).
	defb 147
	defb 2	; New Instrument (2).
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track20:
	defb 235
	defb 15	; New Instrument (15).
	defb 21	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 11	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 24	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 18	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 12	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 11	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 17	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 18	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 12	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 11	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 17	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 12	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track21:
	defb 235
	defb 7	; New Instrument (7).
	defb 16	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 50
	defb 60	; Waits for 1 line.

	defb 53
	defb 60	; Waits for 1 line.

	defb 52
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 53
	defb 60	; Waits for 1 line.

	defb 52
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 52
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track22:
	defb 128
	defb 0	; New Instrument (0).
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track23:
	defb 247
	defb 10	; New Instrument (10).
	defb 20	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track24:
	defb 214
	defb 1	; New Instrument (1).
	defb 7	; Index to an effect block.
	defb 22
	defb 23
	defb 23
	defb 25
	defb 26
	defb 19
	defb 19
	defb 19
	defb 19
	defb 19
	defb 19
	defb 23
	defb 19
	defb 26
	defb 19
	defb 25
	defb 25
	defb 25
	defb 25
	defb 27
	defb 28
	defb 22
	defb 22
	defb 22
	defb 22
	defb 22
	defb 21
	defb 20
	defb 19
	defb 18
	defb 17
	defb 61, 127	; Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track25:
	defb 255
	defb 72	; Escape note (72).
	defb 12	; New Instrument (12).
	defb 8	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


; The speed tracks
AHarmlessGrenade_Subsong0_SpeedTrack0:
	defb 255	; Wait for 128 lines.

; The event tracks
AHarmlessGrenade_Subsong0_EventTrack0:
	defb 255	; Wait for 128 lines.

AHarmlessGrenade_Subsong0_DisarkByteRegionEnd0:
