; You never can tell, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Younevercantell_Start:
Younevercantell_StartDisarkGenerateExternalLabel:

Younevercantell_DisarkByteRegionStart0:
	defb "AT20"
Younevercantell_DisarkPointerRegionStart1:
	defw Younevercantell_ArpeggioTable	; The address of the Arpeggio table.
	defw Younevercantell_PitchTable	; The address of the Pitch table.
	defw Younevercantell_InstrumentTable	; The address of the Instrument table.
	defw Younevercantell_EffectBlockTable	; The address of the Effect Block table.
Younevercantell_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
Younevercantell_DisarkPointerRegionStart2:
	defw Younevercantell_Subsong0_Start
Younevercantell_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
Younevercantell_ArpeggioTable:
Younevercantell_DisarkPointerRegionStart3:
	defw Younevercantell_Arpeggio1
	defw Younevercantell_Arpeggio2
	defw Younevercantell_Arpeggio3
Younevercantell_DisarkPointerRegionEnd3:

Younevercantell_Arpeggio1:
	defb 2	; The speed.

	defb 7
	defb 4
	defb 0
	defb -128
Younevercantell_DisarkWordForceReference4:
	defw Younevercantell_Arpeggio1 + 0 + 1	; Loop.

Younevercantell_Arpeggio2:
	defb 2	; The speed.

	defb 4
	defb 0
	defb -5
	defb -128
Younevercantell_DisarkWordForceReference5:
	defw Younevercantell_Arpeggio2 + 0 + 1	; Loop.

Younevercantell_Arpeggio3:
	defb 2	; The speed.

	defb 0
	defb -5
	defb -8
	defb -128
Younevercantell_DisarkWordForceReference6:
	defw Younevercantell_Arpeggio3 + 0 + 1	; Loop.

; Declares all the Pitches.
Younevercantell_PitchTable:
Younevercantell_DisarkPointerRegionStart7:
	defw Younevercantell_Pitch1
Younevercantell_DisarkPointerRegionEnd7:

Younevercantell_Pitch1:
	defb 1	; The speed.

	defw -2
Younevercantell_Pitch1_GotoNextForLine0:
Younevercantell_DisarkWordForceReference8:
	defw Younevercantell_Pitch1_GotoNextForLine0 + 2
	defw -4
Younevercantell_Pitch1_GotoNextForLine1:
Younevercantell_DisarkWordForceReference9:
	defw Younevercantell_Pitch1_GotoNextForLine1 + 2
	defw -2
Younevercantell_Pitch1_GotoNextForLine2:
Younevercantell_DisarkWordForceReference10:
	defw Younevercantell_Pitch1_GotoNextForLine2 + 2
	defw 0
Younevercantell_Pitch1_GotoNextForLine3:
Younevercantell_DisarkWordForceReference11:
	defw Younevercantell_Pitch1_GotoNextForLine3 + 2
	defw 2
Younevercantell_Pitch1_GotoNextForLine4:
Younevercantell_DisarkWordForceReference12:
	defw Younevercantell_Pitch1_GotoNextForLine4 + 2
	defw 4
Younevercantell_Pitch1_GotoNextForLine5:
Younevercantell_DisarkWordForceReference13:
	defw Younevercantell_Pitch1_GotoNextForLine5 + 2
	defw 2
Younevercantell_Pitch1_GotoNextForLine6:
Younevercantell_DisarkWordForceReference14:
	defw Younevercantell_Pitch1_GotoNextForLine6 + 2
	defw 0
Younevercantell_DisarkWordForceReference15:
	defw Younevercantell_Pitch1 + 4 * 0 + 1

; Declares all the Instruments.
Younevercantell_InstrumentTable:
Younevercantell_DisarkPointerRegionStart16:
	defw Younevercantell_EmptyInstrument
	defw Younevercantell_Instrument1
	defw Younevercantell_Instrument2
	defw Younevercantell_Instrument3
	defw Younevercantell_Instrument4
	defw Younevercantell_Instrument5
	defw Younevercantell_Instrument6
	defw Younevercantell_Instrument7
	defw Younevercantell_Instrument8
Younevercantell_DisarkPointerRegionEnd16:

Younevercantell_EmptyInstrument:
	defb 0	; The speed (>0, 0 for 256).
Younevercantell_EmptyInstrument_Loop:	defb 0	; No Soft no Hard. Volume: 0. Noise? false.

	defb 6	; Loop to silence.

Younevercantell_Instrument1:
	defb 1	; The speed (>0, 0 for 256).
	defb 97	; Soft only. Volume: 12.
	defb 159	; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
	defw 956	; Forced period.

	defb 113	; Soft only. Volume: 14.
	defb 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	defw 1012	; Forced period.

	defb 113	; Soft only. Volume: 14.
	defb 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	defw 1276	; Forced period.

	defb 113	; Soft only. Volume: 14.
	defb 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	defw 1517	; Forced period.

	defb 97	; Soft only. Volume: 12.
	defb 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	defw 2408	; Forced period.

	defb 6	; Loop to silence.

Younevercantell_Instrument2:
	defb 1	; The speed (>0, 0 for 256).
	defb 105	; Soft only. Volume: 13.
	defb 145	; Additional data. Noise: 17. Pitch? false. Arp? false. Period? true.
	defw 426	; Forced period.

	defb 105	; Soft only. Volume: 13.
	defb 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	defw 536	; Forced period.

	defb 97	; Soft only. Volume: 12.
	defb 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	defw 638	; Forced period.

	defb 97	; Soft only. Volume: 12.
	defb 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	defw 716	; Forced period.

	defb 216	; No Soft no Hard. Volume: 11. Noise? true.
	defb 13	; Noise: 13.

	defb 208	; No Soft no Hard. Volume: 10. Noise? true.
	defb 13	; Noise: 13.

	defb 6	; Loop to silence.

Younevercantell_Instrument3:
	defb 1	; The speed (>0, 0 for 256).
	defb 241	; Soft only. Volume: 14. Volume only.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 209	; Soft only. Volume: 10. Volume only.

Younevercantell_Instrument3_Loop:	defb 201	; Soft only. Volume: 9. Volume only.

	defb 7	; Loop.
Younevercantell_DisarkWordForceReference17:
	defw Younevercantell_Instrument3_Loop	; Loop here.

Younevercantell_Instrument4:
	defb 1	; The speed (>0, 0 for 256).
	defb 97	; Soft only. Volume: 12.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 233	; Soft only. Volume: 13. Volume only.

	defb 225	; Soft only. Volume: 12. Volume only.

Younevercantell_Instrument4_Loop:	defb 217	; Soft only. Volume: 11. Volume only.

	defb 7	; Loop.
Younevercantell_DisarkWordForceReference18:
	defw Younevercantell_Instrument4_Loop	; Loop here.

Younevercantell_Instrument5:
	defb 2	; The speed (>0, 0 for 256).
	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb -12	; Arpeggio.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb -12	; Arpeggio.

	defb 209	; Soft only. Volume: 10. Volume only.

Younevercantell_Instrument5_Loop:	defb 73	; Soft only. Volume: 9.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb -12	; Arpeggio.

	defb 201	; Soft only. Volume: 9. Volume only.

	defb 7	; Loop.
Younevercantell_DisarkWordForceReference19:
	defw Younevercantell_Instrument5_Loop	; Loop here.

Younevercantell_Instrument6:
	defb 1	; The speed (>0, 0 for 256).
	defb 81	; Soft only. Volume: 10.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 73	; Soft only. Volume: 9.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

Younevercantell_Instrument6_Loop:	defb 57	; Soft only. Volume: 7.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 7	; Loop.
Younevercantell_DisarkWordForceReference20:
	defw Younevercantell_Instrument6_Loop	; Loop here.

Younevercantell_Instrument7:
	defb 1	; The speed (>0, 0 for 256).
	defb 233	; Soft only. Volume: 13. Volume only.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 217	; Soft only. Volume: 11. Volume only.

	defb 209	; Soft only. Volume: 10. Volume only.

	defb 201	; Soft only. Volume: 9. Volume only.

Younevercantell_Instrument7_Loop:	defb 193	; Soft only. Volume: 8. Volume only.

	defb 7	; Loop.
Younevercantell_DisarkWordForceReference21:
	defw Younevercantell_Instrument7_Loop	; Loop here.

Younevercantell_Instrument8:
	defb 2	; The speed (>0, 0 for 256).
	defb 105	; Soft only. Volume: 13.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 225	; Soft only. Volume: 12. Volume only.

	defb 89	; Soft only. Volume: 11.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 209	; Soft only. Volume: 10. Volume only.

	defb 73	; Soft only. Volume: 9.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

Younevercantell_Instrument8_Loop:	defb 193	; Soft only. Volume: 8. Volume only.

	defb 65	; Soft only. Volume: 8.
	defb 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	defb 12	; Arpeggio.

	defb 7	; Loop.
Younevercantell_DisarkWordForceReference22:
	defw Younevercantell_Instrument8_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
Younevercantell_EffectBlockTable:
Younevercantell_DisarkPointerRegionStart23:
	defw Younevercantell_EffectBlock_P14P96P0	; Index 0
	defw Younevercantell_EffectBlock_P5P0P10P0	; Index 1
	defw Younevercantell_EffectBlock_P4P0	; Index 2
	defw Younevercantell_EffectBlock_P5P0P12	; Index 3
	defw Younevercantell_EffectBlock_P12	; Index 4
	defw Younevercantell_EffectBlock_P5P0P18P0P3	; Index 5
	defw Younevercantell_EffectBlock_P6P0	; Index 6
	defw Younevercantell_EffectBlock_P5P0P13P8	; Index 7
	defw Younevercantell_EffectBlock_P10P0	; Index 8
	defw Younevercantell_EffectBlock_P8	; Index 9
	defw Younevercantell_EffectBlock_P14P32P0	; Index 10
	defw Younevercantell_EffectBlock_P4P1	; Index 11
	defw Younevercantell_EffectBlock_P5P0P18P0P4	; Index 12
	defw Younevercantell_EffectBlock_P6P2	; Index 13
	defw Younevercantell_EffectBlock_P24P60P0P2	; Index 14
	defw Younevercantell_EffectBlock_P24P60P0P3	; Index 15
	defw Younevercantell_EffectBlock_P5P0P11P0P24P59P0P3	; Index 16
	defw Younevercantell_EffectBlock_P24P55P0P3	; Index 17
	defw Younevercantell_EffectBlock_P24P59P0P3	; Index 18
	defw Younevercantell_EffectBlock_P24P59P0P4	; Index 19
	defw Younevercantell_EffectBlock_P5P0P13P19P0P8P8	; Index 20
	defw Younevercantell_EffectBlock_P6P1	; Index 21
	defw Younevercantell_EffectBlock_P5P0P24P57P0P5	; Index 22
	defw Younevercantell_EffectBlock_P5P0P24P59P0P4	; Index 23
	defw Younevercantell_EffectBlock_P5P0P13P18P0P2	; Index 24
	defw Younevercantell_EffectBlock_P5P0P13P18P0P3	; Index 25
	defw Younevercantell_EffectBlock_P18P0P3	; Index 26
	defw Younevercantell_EffectBlock_P15P96P0P10P0	; Index 27
	defw Younevercantell_EffectBlock_P5P0P18P0P2	; Index 28
	defw Younevercantell_EffectBlock_P24P55P0P8	; Index 29
	defw Younevercantell_EffectBlock_P24P57P0P3	; Index 30
	defw Younevercantell_EffectBlock_P24P57P0P4	; Index 31
	defw Younevercantell_EffectBlock_P5P1P13P8	; Index 32
	defw Younevercantell_EffectBlock_P18P0P4	; Index 33
Younevercantell_DisarkPointerRegionEnd23:

Younevercantell_EffectBlock_P8:
	defb 8
Younevercantell_EffectBlock_P12:
	defb 12
Younevercantell_EffectBlock_P4P0:
	defb 4, 0
Younevercantell_EffectBlock_P4P1:
	defb 4, 1
Younevercantell_EffectBlock_P6P0:
	defb 6, 0
Younevercantell_EffectBlock_P6P1:
	defb 6, 1
Younevercantell_EffectBlock_P6P2:
	defb 6, 2
Younevercantell_EffectBlock_P24P60P0P2:
	defb 24, 60, 0, 2
Younevercantell_EffectBlock_P24P60P0P3:
	defb 24, 60, 0, 3
Younevercantell_EffectBlock_P5P0P24P57P0P5:
	defb 5, 0, 24, 57, 0, 5
Younevercantell_EffectBlock_P5P0P24P59P0P4:
	defb 5, 0, 24, 59, 0, 4
Younevercantell_EffectBlock_P5P0P13P19P0P8P8:
	defb 5, 0, 13, 19, 0, 8, 8
Younevercantell_EffectBlock_P5P0P18P0P2:
	defb 5, 0, 18, 0, 2
Younevercantell_EffectBlock_P5P0P18P0P3:
	defb 5, 0, 18, 0, 3
Younevercantell_EffectBlock_P5P0P18P0P4:
	defb 5, 0, 18, 0, 4
Younevercantell_EffectBlock_P5P0P10P0:
	defb 5, 0, 10, 0
Younevercantell_EffectBlock_P5P0P13P8:
	defb 5, 0, 13, 8
Younevercantell_EffectBlock_P14P32P0:
	defb 14, 32, 0
Younevercantell_EffectBlock_P14P96P0:
	defb 14, 96, 0
Younevercantell_EffectBlock_P5P0P13P18P0P2:
	defb 5, 0, 13, 18, 0, 2
Younevercantell_EffectBlock_P5P0P13P18P0P3:
	defb 5, 0, 13, 18, 0, 3
Younevercantell_EffectBlock_P18P0P3:
	defb 18, 0, 3
Younevercantell_EffectBlock_P18P0P4:
	defb 18, 0, 4
Younevercantell_EffectBlock_P5P0P11P0P24P59P0P3:
	defb 5, 0, 11, 0, 24, 59, 0, 3
Younevercantell_EffectBlock_P24P55P0P3:
	defb 24, 55, 0, 3
Younevercantell_EffectBlock_P24P55P0P8:
	defb 24, 55, 0, 8
Younevercantell_EffectBlock_P24P57P0P3:
	defb 24, 57, 0, 3
Younevercantell_EffectBlock_P24P57P0P4:
	defb 24, 57, 0, 4
Younevercantell_EffectBlock_P5P1P13P8:
	defb 5, 1, 13, 8
Younevercantell_EffectBlock_P15P96P0P10P0:
	defb 15, 96, 0, 10, 0
Younevercantell_EffectBlock_P24P59P0P3:
	defb 24, 59, 0, 3
Younevercantell_EffectBlock_P24P59P0P4:
	defb 24, 59, 0, 4
Younevercantell_EffectBlock_P10P0:
	defb 10, 0
Younevercantell_EffectBlock_P5P0P12:
	defb 5, 0, 12

Younevercantell_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
Younevercantell_Subsong0_DisarkByteRegionStart0:
Younevercantell_Subsong0_Start:
	defb 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	defb 1	; Digichannel (0-2).
	defb 1	; PSG count (>0).
	defb 42	; Loop start index (>=0).
	defb 57	; End index (>=0).
	defb 6	; Initial speed (>=0).
	defb 9	; Base note index (>=0).

Younevercantell_Subsong0_Linker:
Younevercantell_Subsong0_DisarkPointerRegionStart1:
; Position 0
	defw Younevercantell_Subsong0_Track13
	defw Younevercantell_Subsong0_Track14
	defw Younevercantell_Subsong0_Track12
	defw Younevercantell_Subsong0_LinkerBlock0

; Position 1
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track1
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 2
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track2
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 3
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track3
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 4
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track5
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 5
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track6
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 6
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track7
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 7
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track8
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 8
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track9
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 9
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track15
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 10
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track16
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 11
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track17
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 12
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track18
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 13
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track19
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 14
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track20
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 15
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track8
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 16
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track9
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 17
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track1
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 18
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track2
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 19
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track3
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 20
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track5
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 21
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track6
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 22
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track7
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 23
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track8
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 24
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track9
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 25
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track15
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 26
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track16
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 27
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track17
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 28
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track18
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 29
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track19
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 30
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track20
	defw Younevercantell_Subsong0_LinkerBlock2

; Position 31
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track8
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 32
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track9
	defw Younevercantell_Subsong0_LinkerBlock3

; Position 33
	defw Younevercantell_Subsong0_Track21
	defw Younevercantell_Subsong0_Track22
	defw Younevercantell_Subsong0_Track23
	defw Younevercantell_Subsong0_LinkerBlock4

; Position 34
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track24
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 35
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track25
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 36
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track26
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 37
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track27
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 38
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track28
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 39
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track29
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 40
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track30
	defw Younevercantell_Subsong0_LinkerBlock1

; Position 41
	defw Younevercantell_Subsong0_Track32
	defw Younevercantell_Subsong0_Track33
	defw Younevercantell_Subsong0_Track31
	defw Younevercantell_Subsong0_LinkerBlock5

; Position 42
Younevercantell_Subsong0_Linker_Loop:
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track1
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 43
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track2
	defw Younevercantell_Subsong0_LinkerBlock7

; Position 44
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track3
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 45
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track5
	defw Younevercantell_Subsong0_LinkerBlock7

; Position 46
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track6
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 47
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track7
	defw Younevercantell_Subsong0_LinkerBlock7

; Position 48
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track8
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 49
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track9
	defw Younevercantell_Subsong0_LinkerBlock7

; Position 50
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track15
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 51
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track16
	defw Younevercantell_Subsong0_LinkerBlock7

; Position 52
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track17
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 53
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track18
	defw Younevercantell_Subsong0_LinkerBlock7

; Position 54
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track19
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 55
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track20
	defw Younevercantell_Subsong0_LinkerBlock7

; Position 56
	defw Younevercantell_Subsong0_Track4
	defw Younevercantell_Subsong0_Track11
	defw Younevercantell_Subsong0_Track8
	defw Younevercantell_Subsong0_LinkerBlock6

; Position 57
	defw Younevercantell_Subsong0_Track0
	defw Younevercantell_Subsong0_Track10
	defw Younevercantell_Subsong0_Track9
	defw Younevercantell_Subsong0_LinkerBlock7

Younevercantell_Subsong0_DisarkPointerRegionEnd1:
	defw 0	; Loop.
Younevercantell_Subsong0_DisarkWordForceReference2:
	defw Younevercantell_Subsong0_Linker_Loop

Younevercantell_Subsong0_LinkerBlock0:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference3:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference4:
	defw Younevercantell_Subsong0_EventTrack0	; EventTrack address.
Younevercantell_Subsong0_LinkerBlock1:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference5:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference6:
	defw Younevercantell_Subsong0_EventTrack1	; EventTrack address.
Younevercantell_Subsong0_LinkerBlock2:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference7:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference8:
	defw Younevercantell_Subsong0_EventTrack2	; EventTrack address.
Younevercantell_Subsong0_LinkerBlock3:
	defb 16	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference9:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference10:
	defw Younevercantell_Subsong0_EventTrack2	; EventTrack address.
Younevercantell_Subsong0_LinkerBlock4:
	defb 16	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference11:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference12:
	defw Younevercantell_Subsong0_EventTrack1	; EventTrack address.
Younevercantell_Subsong0_LinkerBlock5:
	defb 32	; Height.
	defb 0	; Transposition 0.
	defb 0	; Transposition 1.
	defb 0	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference13:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference14:
	defw Younevercantell_Subsong0_EventTrack3	; EventTrack address.
Younevercantell_Subsong0_LinkerBlock6:
	defb 32	; Height.
	defb 2	; Transposition 0.
	defb 2	; Transposition 1.
	defb 2	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference15:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference16:
	defw Younevercantell_Subsong0_EventTrack1	; EventTrack address.
Younevercantell_Subsong0_LinkerBlock7:
	defb 32	; Height.
	defb 2	; Transposition 0.
	defb 2	; Transposition 1.
	defb 2	; Transposition 2.
Younevercantell_Subsong0_DisarkWordForceReference17:
	defw Younevercantell_Subsong0_SpeedTrack0	; SpeedTrack address.
Younevercantell_Subsong0_DisarkWordForceReference18:
	defw Younevercantell_Subsong0_EventTrack2	; EventTrack address.

Younevercantell_Subsong0_Track0:
	defb 207
	defb 3	; New Instrument (3).
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 19
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track1:
	defb 242
	defb 4	; New Instrument (4).
	defb 24	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 14	; Index to an effect block.
	defb 48
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 16	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 110
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 22	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 112
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 112
	defb 1	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 107
	defb 4	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 8	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track2:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 234
	defb 5	; New Instrument (5).
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 4	; Index to an effect block.
	defb 43
	defb 128
	defb 0	; New Instrument (0).
	defb 173
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 46
	defb 128
	defb 0	; New Instrument (0).
	defb 179
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 128
	defb 0	; New Instrument (0).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 240
	defb 4	; New Instrument (4).
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 114
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 114
	defb 5	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 15	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track3:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 240
	defb 4	; New Instrument (4).
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 112
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 23	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 112
	defb 1	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 107
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 43
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 109
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 108
	defb 1	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track4:
	defb 138
	defb 3	; New Instrument (3).
	defb 60	; Waits for 1 line.

	defb 10
	defb 60	; Waits for 1 line.

	defb 13
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 13
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 10
	defb 60	; Waits for 1 line.

	defb 10
	defb 60	; Waits for 1 line.

	defb 13
	defb 60	; Waits for 1 line.

	defb 14
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 17
	defb 60	; Waits for 1 line.

	defb 13
	defb 60	; Waits for 1 line.

	defb 14
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track5:
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 230
	defb 5	; New Instrument (5).
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 128
	defb 0	; New Instrument (0).
	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 41
	defb 128
	defb 0	; New Instrument (0).
	defb 174
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 128
	defb 0	; New Instrument (0).
	defb 169
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 6	; Waits for 7 lines.

	defb 174
	defb 4	; New Instrument (4).
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 113
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track6:
	defb 241
	defb 4	; New Instrument (4).
	defb 25	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 18	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 8	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 3	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 108
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 108
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 109
	defb 5	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 17	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 107
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 108
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 109
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 109
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 108
	defb 1	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track7:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 230
	defb 5	; New Instrument (5).
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 128
	defb 0	; New Instrument (0).
	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 41
	defb 128
	defb 0	; New Instrument (0).
	defb 174
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 128
	defb 0	; New Instrument (0).
	defb 169
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 6	; Waits for 7 lines.

	defb 240
	defb 4	; New Instrument (4).
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 113
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 113
	defb 12	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 19	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track8:
	defb 124	; No note, but effects.
	defb 27	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 238
	defb 4	; New Instrument (4).
	defb 3	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 111
	defb 5	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 30	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 108
	defb 4	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 108
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 119
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 119
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 119
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 119
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track9:
	defb 242
	defb 4	; New Instrument (4).
	defb 5	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 15	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 234
	defb 5	; New Instrument (5).
	defb 4	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 43
	defb 128
	defb 0	; New Instrument (0).
	defb 170
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 43
	defb 128
	defb 0	; New Instrument (0).
	defb 170
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 43
	defb 128
	defb 0	; New Instrument (0).
	defb 167
	defb 5	; New Instrument (5).
	defb 128
	defb 0	; New Instrument (0).
	defb 164
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 34
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 174
	defb 4	; New Instrument (4).
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 114
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track10:
	defb 195
	defb 1	; New Instrument (1).
	defb 7	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 236
	defb 6	; New Instrument (6).
	defb 21	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 195
	defb 1	; New Instrument (1).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 236
	defb 6	; New Instrument (6).
	defb 21	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track11:
	defb 195
	defb 1	; New Instrument (1).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 238
	defb 6	; New Instrument (6).
	defb 13	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 238
	defb 6	; New Instrument (6).
	defb 13	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 195
	defb 1	; New Instrument (1).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 238
	defb 6	; New Instrument (6).
	defb 13	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 238
	defb 6	; New Instrument (6).
	defb 13	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track12:
	defb 236
	defb 7	; New Instrument (7).
	defb 20	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 29	; Index to an effect block.
	defb 55
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 55
	defb 60	; Waits for 1 line.

	defb 45
	defb 60	; Waits for 1 line.

	defb 54
	defb 60	; Waits for 1 line.

	defb 44
	defb 60	; Waits for 1 line.

	defb 53
	defb 60	; Waits for 1 line.

	defb 43
	defb 60	; Waits for 1 line.

	defb 51
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 10	; Index to an effect block.
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 238
	defb 4	; New Instrument (4).
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 114
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track13:
	defb 128
	defb 0	; New Instrument (0).
	defb 61, 14	; Waits for 15 lines.

	defb 238
	defb 7	; New Instrument (7).
	defb 32	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 10	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 98
	defb 11	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 10	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track14:
	defb 128
	defb 0	; New Instrument (0).
	defb 61, 20	; Waits for 21 lines.

	defb 202
	defb 7	; New Instrument (7).
	defb 7	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 10	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track15:
	defb 243
	defb 4	; New Instrument (4).
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 115
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 114
	defb 28	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 14	; Index to an effect block.
	defb 62 + 2 * 64	; Optimized wait for 4 lines.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 33	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 31	; Index to an effect block.
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 109
	defb 26	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 17	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track16:
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 235
	defb 4	; New Instrument (4).
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 170
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 43
	defb 128
	defb 0	; New Instrument (0).
	defb 173
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 46
	defb 128
	defb 0	; New Instrument (0).
	defb 179
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 49
	defb 60	; Waits for 1 line.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 128
	defb 0	; New Instrument (0).
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 238
	defb 4	; New Instrument (4).
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 115
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track17:
	defb 243
	defb 4	; New Instrument (4).
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 115
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 115
	defb 2	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 115
	defb 1	; Index to an effect block.
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 3	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 112
	defb 26	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 18	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track18:
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 174
	defb 4	; New Instrument (4).
	defb 60	; Waits for 1 line.

	defb 230
	defb 5	; New Instrument (5).
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 128
	defb 0	; New Instrument (0).
	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 41
	defb 128
	defb 0	; New Instrument (0).
	defb 174
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 128
	defb 0	; New Instrument (0).
	defb 169
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 6	; Waits for 7 lines.

	defb 174
	defb 4	; New Instrument (4).
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 113
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track19:
	defb 242
	defb 4	; New Instrument (4).
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 4	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 112
	defb 2	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 43
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 108
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 45
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 110
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 110
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 46
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 112
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 114
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 62 + 0 * 64	; Optimized wait for 2 lines.

	defb 110
	defb 2	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track20:
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 230
	defb 5	; New Instrument (5).
	defb 3	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 128
	defb 0	; New Instrument (0).
	defb 168
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 41
	defb 128
	defb 0	; New Instrument (0).
	defb 174
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 44
	defb 128
	defb 0	; New Instrument (0).
	defb 169
	defb 5	; New Instrument (5).
	defb 60	; Waits for 1 line.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 6	; Waits for 7 lines.

	defb 240
	defb 4	; New Instrument (4).
	defb 8	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 113
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 113
	defb 12	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 19	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track21:
	defb 214
	defb 3	; New Instrument (3).
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 86
	defb 11	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 86
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 86
	defb 11	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 86
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 86
	defb 11	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 86
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 86
	defb 11	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track22:
	defb 195
	defb 1	; New Instrument (1).
	defb 7	; Index to an effect block.
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 3
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 3
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 3
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track23:
	defb 167
	defb 5	; New Instrument (5).
	defb 128
	defb 0	; New Instrument (0).
	defb 164
	defb 5	; New Instrument (5).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 34
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 174
	defb 8	; New Instrument (8).
	defb 60	; Waits for 1 line.

	defb 48
	defb 60	; Waits for 1 line.

	defb 50
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track24:
	defb 179
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 60	; Waits for 1 line.

	defb 50
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 46
	defb 60	; Waits for 1 line.

	defb 48
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 39
	defb 60	; Waits for 1 line.

	defb 41
	defb 43
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track25:
	defb 61, 15	; Waits for 16 lines.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 8	; Waits for 9 lines.

	defb 174
	defb 8	; New Instrument (8).
	defb 60	; Waits for 1 line.

	defb 48
	defb 60	; Waits for 1 line.

	defb 50
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track26:
	defb 179
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 48
	defb 60	; Waits for 1 line.

	defb 50
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 46
	defb 60	; Waits for 1 line.

	defb 48
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 60	; Waits for 1 line.

	defb 44
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track27:
	defb 61, 15	; Waits for 16 lines.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 8	; Waits for 9 lines.

	defb 174
	defb 8	; New Instrument (8).
	defb 60	; Waits for 1 line.

	defb 48
	defb 60	; Waits for 1 line.

	defb 49
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track28:
	defb 178
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 60	; Waits for 1 line.

	defb 48
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 41
	defb 60	; Waits for 1 line.

	defb 46
	defb 61, 6	; Waits for 7 lines.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 45
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track29:
	defb 172
	defb 8	; New Instrument (8).
	defb 61, 16	; Waits for 17 lines.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 6	; Waits for 7 lines.

	defb 174
	defb 8	; New Instrument (8).
	defb 60	; Waits for 1 line.

	defb 48
	defb 60	; Waits for 1 line.

	defb 49
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track30:
	defb 178
	defb 8	; New Instrument (8).
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 46
	defb 60	; Waits for 1 line.

	defb 48
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 43
	defb 60	; Waits for 1 line.

	defb 46
	defb 62 + 3 * 64	; Optimized wait for 5 lines.

	defb 41
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 44
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 41
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track31:
	defb 167
	defb 8	; New Instrument (8).
	defb 61, 16	; Waits for 17 lines.

	defb 128
	defb 0	; New Instrument (0).
	defb 61, 6	; Waits for 7 lines.

	defb 240
	defb 4	; New Instrument (4).
	defb 3	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 114
	defb 1	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 116
	defb 4	; Index to an effect block.
	defb 124	; No note, but effects.
	defb 0	; Index to an effect block.
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track32:
	defb 207
	defb 3	; New Instrument (3).
	defb 2	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 15
	defb 60	; Waits for 1 line.

	defb 18
	defb 60	; Waits for 1 line.

	defb 19
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 22
	defb 60	; Waits for 1 line.

	defb 23
	defb 60	; Waits for 1 line.

	defb 23
	defb 61, 127	; Waits for 128 lines.


Younevercantell_Subsong0_Track33:
	defb 195
	defb 1	; New Instrument (1).
	defb 7	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 5
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 39
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 236
	defb 6	; New Instrument (6).
	defb 21	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 195
	defb 1	; New Instrument (1).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 231
	defb 6	; New Instrument (6).
	defb 6	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 197
	defb 2	; New Instrument (2).
	defb 9	; Index to an effect block.
	defb 60	; Waits for 1 line.

	defb 5
	defb 62 + 1 * 64	; Optimized wait for 3 lines.

	defb 131
	defb 1	; New Instrument (1).
	defb 60	; Waits for 1 line.

	defb 133
	defb 2	; New Instrument (2).
	defb 61, 127	; Waits for 128 lines.


; The speed tracks
Younevercantell_Subsong0_SpeedTrack0:
	defb 10	; Value: 5.
	defb 1	; Wait for 1 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 3	; Wait for 2 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 3	; Wait for 2 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 3	; Wait for 2 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 3	; Wait for 2 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 3	; Wait for 2 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 3	; Wait for 2 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 3	; Wait for 2 lines.
	defb 8	; Value: 4.
	defb 10	; Value: 5.
	defb 191	; Wait for 96 lines.

; The event tracks
Younevercantell_Subsong0_EventTrack0:
	defb 0	; Escape code.
	defb 249	; Escaped value.
	defb 0	; Escape code.
	defb 246	; Escaped value.
	defb 27	; Wait for 14 lines.
	defb 0	; Escape code.
	defb 252	; Escaped value.
	defb 27	; Wait for 14 lines.
	defb 0	; Escape code.
	defb 244	; Escaped value.
	defb 191	; Wait for 96 lines.
Younevercantell_Subsong0_EventTrack1:
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 197	; Wait for 99 lines.
Younevercantell_Subsong0_EventTrack2:
	defb 2	; Value: 1.
	defb 3	; Wait for 2 lines.
	defb 0	; Escape code.
	defb 241	; Escaped value.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 1	; Wait for 1 lines.
	defb 0	; Escape code.
	defb 249	; Escaped value.
	defb 1	; Wait for 1 lines.
	defb 4	; Value: 2.
	defb 197	; Wait for 99 lines.
Younevercantell_Subsong0_EventTrack3:
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 5	; Wait for 3 lines.
	defb 4	; Value: 2.
	defb 5	; Wait for 3 lines.
	defb 2	; Value: 1.
	defb 1	; Wait for 1 lines.
	defb 0	; Escape code.
	defb 249	; Escaped value.
	defb 1	; Wait for 1 lines.
	defb 4	; Value: 2.
	defb 197	; Wait for 99 lines.

Younevercantell_Subsong0_DisarkByteRegionEnd0:
